knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"'
        options:
            - { name: 'enable-local-file-access', value: true }
    image:
        enabled: true
        binary: '"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe"'
        options:
            - { name: 'enable-local-file-access', value: true }
